### ISSUE TITLE
Feature Request for Automated Pull

### ISSUE THREAD

**Issue by ArchitectingSoftware** [drexel-systems/SysProg-Class#1]
@bdlilley - Love the automation.  Im wondering if we could add a root directory to the repo called `assignments`.  Under that we pull over HWx/starter.   For each assignment in the solutions repo we use a convention HWx/starter and HWx/solution where starter has the directions or skeleton code to get started.  It might also be a good idea, and easier if we restructure the solution repo to follow the same model aka use /assignments as a root directory.

**Comment by bdlilley** [comment]
Done!
